GradeBook class
diosquierra/OOP pull request #4
Opened 2020-10-28 22:43 UTC by diosquierra

This is GradeBook class.

2020-10-30 15:10 UTC, shadrina requested changes
В общем и целом все ок, замечания достаточно минорные. 

На этой лабе и в следующих уже желательно поактивнее использовать возможности стандартной библиотеки. Например, коллекции, Stream API и т.д.

2020-10-30 15:10 UTC, shadrina commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +        code = (int) subjectCode.get(subjectName);
Если бы была мапа была правильно инициализирована, касты бы не понадобились.

2020-10-30 15:10 UTC, shadrina commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +        if(markDiplomaWork == 5 && markForDiplomaCheck() && ifNoMarkThree()){
`return markDiplomaWork == 5 && markForDiplomaCheck() && ifNoMarkThree();`

2020-10-30 15:10 UTC, shadrina commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +        if((countFives / countMarks) * 100 >= 75){
`return (countFives / countMarks) * 100 >= 75`

2020-10-30 15:10 UTC, shadrina commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +class Subject{
В джаве желательно разные классы разносить по разным файлам.

2020-10-30 15:10 UTC, shadrina commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +    int[] grades = new int[9];
Я бы тут тоже использовала просто List наверно. Вроде как ничего плохого не произойдет, если нигде не будет упомянуто число 9 (хотя это неочевидно, надо подумать).

В крайнем случае можно внутри `putMark` проверять, не превышено ли максимальное количество оценок.

2020-10-30 15:10 UTC, shadrina commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +        for(int mark : grades){
Опять же, если бы grades был списком, можно было бы красиво написать `return grades.stream().filter(mark -> mark == 5).count()`. 

Ну это просто рекомендация.

2020-10-31 09:11 UTC, diosquierra commented on grade_book/src/main/java/nsu/oop/gradeBook/GradeBook.java
> +    Subject[] subjectList = new Subject[50];
lastPoint нужен не только для записи в массив, но и для хэш таблицы, там записывается где какой предмет хранится при помощи lastPoint.

2020-11-06 14:48 UTC, shadrina approved these changes

2020-11-09 16:31 UTC, merged