Task 3.1
diosquierra/OOP pull request #5
Opened 2020-11-26 19:50 UTC by diosquierra

This is Gregorian Calendar.

2020-11-27 15:52 UTC, shadrina requested changes
Код выполняет свои задачи, это отлично, но мы с вами учимся писать еще и красиво. Значит, надо избавляться от сишного стиля и привычки писать быстро и жертвовать качеством кода (возможно, ты занимался олимпиадным программированием, и это осталось оттуда).

Я стараюсь не требовать идеального стиля, но делать декомпозицию и использовать возможности языка вы после этого курса должны научиться.

2020-11-27 15:52 UTC, shadrina commented on calendar/src/main/java/nsu/oop/calendar/GregorianCalendar.java
> +        }
Объясняю, как жизнь станет лучше с наличием enum'ов.
Если у тебя есть даже что-то вот настолько простое:
```
enum DayOfWeek {
    MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
}
``` 

У тебя уже появляются возможности делать вот такие штуки:
```
System.out.println(DayOfWeek.MONDAY.name()); // "MONDAY" (строку можно привести в желаемый регистр с помощью методов класса String)
System.out.println(DayOfWeek.values()[0]); // DayOfWeek.MONDAY
```

А это еще самый простейший enum, в джаве с ними можно делать штуки интереснее.

2020-11-27 15:52 UTC, shadrina commented on calendar/src/main/java/nsu/oop/calendar/GregorianCalendar.java
> +                monthOffset = 6;
А точно нельзя этот офсет получить по какой-то более компактной формуле, а не через громадный свич?

2020-11-29 12:14 UTC, diosquierra commented on calendar/src/main/java/nsu/oop/calendar/GregorianCalendar.java
> +                monthOffset = 6;
Его можно получить рекурсивно.

2020-12-05 14:41 UTC, shadrina approved these changes

2020-12-07 10:17 UTC, merged