My Calculator
diosquierra/OOP pull request #7
Opened 2020-12-29 06:30 UTC by diosquierra

2020-12-29 11:27 UTC, shadrina requested changes

2020-12-29 11:27 UTC, shadrina commented on Calculator/src/main/java/MyCalculator.java
> +class SinOperator implements CalcOperator {
Каждый такой оператор лучше вынести в отдельный файл. В Джаве обычно один класс - один файл

2020-12-29 11:27 UTC, shadrina commented on Calculator/src/main/java/MyCalculator.java
> +import java.util.Stack;
https://stackoverflow.com/questions/12524826/why-should-i-use-deque-over-stack

2020-12-30 08:58 UTC, shadrina approved these changes

2020-12-30 08:59 UTC, shadrina commented
Еще одна задача до четверки будет?

2020-12-30 09:14 UTC, diosquierra commented
> е

Да

2020-12-30 09:14 UTC, merged